### ISSUE TITLE
Issue spawning child process on Windows machines 

### ISSUE THREAD

**Issue by johnrjj** [UltimateSoftware/ng6-cli#29]
Whenever attempting to spawn a command with 0.6.x of ng6 on windows, it can fail. 

This is a known issue with node:
https://github.com/nodejs/node-v0.x-archive/issues/2318

**Comment by BenDiuguid** [comment]
I believe this can be fixed with [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) from npm.

I don't have a windows machine to test it on. But I did just change the `ng6 new app -i/--install` to use `cross-spawn`. So you could test it there?

**Comment by johnrjj** [comment]
Sure, I'll test and report back. May not need this PR.

**Comment by BenDiuguid** [comment]
Your PR already landed, but I replaced `spawn` with `cross-spawn` in the latest webpack PR #32

**Comment by johnrjj** [comment]
Oh derp, this is the bug issue not the PR, haha. Sounds good, will test.

**Comment by BenDiuguid** [comment]
I believe this is fixed in the latest version, I'm closing this issue for now, if it's still a problem we can re open it 👍

**Comment by DevarshiDave** [comment]
Its working fine, thank you :)
