### ISSUE TITLE
Use Component Router instead of ui-router.

### ISSUE THREAD

**Issue by asleepinglion** [UltimateSoftware/ng6-cli#9]

**Comment by darkfadr** [comment]
Component Router for Angular is being deprecated as the Angular team is looking to possibly backport the router from Angular 2 into 1.x. 
[https://docs.angularjs.org/guide/component-router](Source reference)

**Comment by asleepinglion** [comment]
Hey thanks for letting me know. I'll go ahead and close the ticket for now.
